# Generated by Django 4.2.2 on 2023-06-10 19:40

import db.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=30, unique=True)),
                ("category_discription", models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
                ("discount_price", models.IntegerField()),
                ("quantity_in_stock", models.IntegerField()),
                (
                    "product_image1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=db.models.product_image_upload_path,
                    ),
                ),
                (
                    "product_image2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=db.models.product_image_upload_path,
                    ),
                ),
                (
                    "product_image3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=db.models.product_image_upload_path,
                    ),
                ),
                (
                    "product_image4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=db.models.product_image_upload_path,
                    ),
                ),
                (
                    "product_image5",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=db.models.product_image_upload_path,
                    ),
                ),
                ("brand", models.CharField(max_length=255)),
                ("dicription", models.TextField(max_length=255)),
                ("is_available", models.BooleanField(default=True)),
                ("product_created", models.DateTimeField(auto_now_add=True)),
                ("product_updated", models.DateTimeField(auto_now=True)),
                (
                    "product_categoty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.category"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
