# Generated by Django 4.2.2 on 2023-06-11 09:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0003_remove_user_is_delivery_partner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="user",
        ),
    ]
